---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xmsixdid/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp disclaimer.html $DEPLOYPATH
    - /bin/cp CNAME $DEPLOYPATH
